### ISSUE TITLE
Tutorial Notebook is Blank

### ISSUE THREAD

**Issue by zctpljs** [patrikgerard/Uncovering-Narratives#1]
Hi all! Apologies we've tried to access your tutorial but it appears blank. Thank you!

**Comment by patrikgerard** [comment]
Our apologies! We just deleted the file and updated the readme to include the [link](https://colab.research.google.com/drive/11PRIrmERbBkf-YZxlCFmiTc5vcYg9iH7?usp=sharing) to the tutorial (on google drive)
